In [4]:
import matplotlib.pyplot as plt
import netCDF4 as nc
import numpy as np
import xarray as xr

%matplotlib inline

In [5]:
imin = 376 - 1  # want 376
imax = 470 # want 470
rim = 10
nxb = np.arange(imin, imax) + 1

In [6]:
consts = ['M2', 'S2', 'N2', 'K2', 'K1', 'O1', 'Q1', 'P1']
directory = '/home/sallen/MEOPAR/tides/west/'
lead = 'SalishSea_N36_AF_west_tide_'
endi = '_grid_T.nc'
newlead = 'SalishSea_N36_long_west_tide_'

In [7]:
# was running, fortran, 381 to 467
# want to run, 380 to 470 so add one to start and 3 to end
addtostart = (381-1) - imin

In [11]:
def pad(xds, v1='z1', v2='z2'):
    nz1 = np.zeros((1, imax-imin))
    nz1[0, addtostart:87+addtostart] = xds[v1][:]
    nz2 = np.zeros((1, imax-imin))
    nz2[0, addtostart:87+addtostart] = xds[v2][:]
    data = {v1: nz1, v2: nz2}
    print(data[v1].shape)
    return data

In [20]:
def make_new_files(v1='z1', v2='z2', endi='_grid_T.nc'):
    for const in consts:
        print (const, directory+lead+const+endi)
        xds = xr.open_dataset(directory+lead+const+endi)
        data = pad(xds, v1=v1, v2=v2)

        da = {}
        for var in [v1, v2]:
            da[var] = xr.DataArray(data=data[var], 
                 name=var,
                 dims=('yb', 'xb'),
                 coords={'yb': [0], 'xb': nxb},
                 attrs=xds[var].attrs)

        ds = xr.Dataset(data_vars={v1: da[v1],
                          v2: da[v2]},
               coords={'yb': [0], 'xb': nxb},
               attrs=xds.attrs)

        ds.to_netcdf(newlead+const+endi)

        print(ds)
    return xds, ds

In [21]:
endi = '_grid_T.nc'
xds, ds = make_new_files(v1='z1', v2='z2', endi=endi)

M2 /home/sallen/MEOPAR/tides/west/SalishSea_N36_AF_west_tide_M2_grid_T.nc
(1, 95)
<xarray.Dataset>
Dimensions:  (xb: 95, yb: 1)
Coordinates:
  * yb       (yb) int64 0
  * xb       (xb) int64 376 377 378 379 380 381 382 383 384 385 386 387 388 ...
Data variables:
    z2       (yb, xb) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...
    z1       (yb, xb) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...
Attributes:
    description:  Tide data from WebTide - K1 phase shifted
S2 /home/sallen/MEOPAR/tides/west/SalishSea_N36_AF_west_tide_S2_grid_T.nc
(1, 95)
<xarray.Dataset>
Dimensions:  (xb: 95, yb: 1)
Coordinates:
  * yb       (yb) int64 0
  * xb       (xb) int64 376 377 378 379 380 381 382 383 384 385 386 387 388 ...
Data variables:
    z2       (yb, xb) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...
    z1       (yb, xb) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...
Attributes:
    description:  Tide data from WebTide - K1 phase shifted
N2 /home/sallen/MEOPAR/tides/west/

In [15]:
endi = '_grid_U.nc'
make_new_files(v1='u1', v2='u2', endi=endi)

M2 /home/sallen/MEOPAR/tides/west/SalishSea_N36_AF_west_tide_M2_grid_U.nc
(1, 95)
<xarray.Dataset>
Dimensions:  (xb: 95, yb: 1)
Coordinates:
  * yb       (yb) int64 0
  * xb       (xb) int64 376 377 378 379 380 381 382 383 384 385 386 387 388 ...
Data variables:
    u2       (yb, xb) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...
    u1       (yb, xb) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -0.135 ...
Attributes:
    description:  Tide data from WebTide - K1 phase shifted
S2 /home/sallen/MEOPAR/tides/west/SalishSea_N36_AF_west_tide_S2_grid_U.nc
(1, 95)
<xarray.Dataset>
Dimensions:  (xb: 95, yb: 1)
Coordinates:
  * yb       (yb) int64 0
  * xb       (xb) int64 376 377 378 379 380 381 382 383 384 385 386 387 388 ...
Data variables:
    u2       (yb, xb) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...
    u1       (yb, xb) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...
Attributes:
    description:  Tide data from WebTide - K1 phase shifted
N2 /home/sallen/MEOPAR/tide

In [16]:
endi = '_grid_V.nc'
make_new_files(v1='v1', v2='v2', endi=endi)

M2 /home/sallen/MEOPAR/tides/west/SalishSea_N36_AF_west_tide_M2_grid_V.nc
(1, 95)
<xarray.Dataset>
Dimensions:  (xb: 95, yb: 1)
Coordinates:
  * yb       (yb) int64 0
  * xb       (xb) int64 376 377 378 379 380 381 382 383 384 385 386 387 388 ...
Data variables:
    v1       (yb, xb) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.08164 ...
    v2       (yb, xb) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.2224 ...
Attributes:
    description:  Tide data from WebTide - K1 phase shifted
S2 /home/sallen/MEOPAR/tides/west/SalishSea_N36_AF_west_tide_S2_grid_V.nc
(1, 95)
<xarray.Dataset>
Dimensions:  (xb: 95, yb: 1)
Coordinates:
  * yb       (yb) int64 0
  * xb       (xb) int64 376 377 378 379 380 381 382 383 384 385 386 387 388 ...
Data variables:
    v1       (yb, xb) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 -0.006629 ...
    v2       (yb, xb) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.05913 ...
Attributes:
    description:  Tide data from WebTide - K1 phase shifted
N2 /home/sallen/M

In [23]:
print (xds)
print (ds)

<xarray.Dataset>
Dimensions:  (xb: 87, yb: 1)
Coordinates:
  * xb       (xb) int32 384 385 386 387 388 389 390 391 392 393 394 395 396 ...
  * yb       (yb) int32 1
Data variables:
    nbidta   (yb, xb) int32 ...
    nbjdta   (yb, xb) int32 ...
    nbrdta   (yb, xb) int32 ...
    z1       (yb, xb) float32 ...
    z2       (yb, xb) float32 ...
Attributes:
    description:  Tide data from WebTide - K1 phase shifted
<xarray.Dataset>
Dimensions:  (xb: 95, yb: 1)
Coordinates:
  * yb       (yb) int64 0
  * xb       (xb) int64 376 377 378 379 380 381 382 383 384 385 386 387 388 ...
Data variables:
    z2       (yb, xb) float64 0.0 0.0 0.0 0.0 0.0 -0.0 -0.0 -0.0 -0.0 -0.0 ...
    z1       (yb, xb) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 ...
Attributes:
    description:  Tide data from WebTide - K1 phase shifted


In [24]:
print(xds.z1[0:10])

<xarray.DataArray 'z1' (yb: 1, xb: 87)>
array([[ 0.      ,  0.      ,  0.      ,  0.      ,  0.      , -0.081714,
        -0.081207, -0.080675, -0.080142, -0.079659, -0.079269, -0.078878,
        -0.078427, -0.077935, -0.077321, -0.076688, -0.076187, -0.075692,
        -0.075172, -0.074682, -0.074205, -0.073758, -0.073327, -0.072898,
        -0.072473, -0.072089, -0.071694, -0.071298, -0.070906, -0.070539,
        -0.070185, -0.069832, -0.069478, -0.069125, -0.068772, -0.068441,
        -0.068111, -0.06778 , -0.067449, -0.067129, -0.066824, -0.066522,
        -0.06623 , -0.065944, -0.06566 , -0.065387, -0.065137, -0.064888,
        -0.06464 , -0.064377, -0.06417 , -0.063967, -0.063759, -0.063552,
        -0.063348, -0.063183, -0.063018, -0.062853, -0.062689, -0.062524,
        -0.062363, -0.062206, -0.062049, -0.061892, -0.061735, -0.061578,
        -0.061411, -0.06124 , -0.06107 , -0.0609  , -0.06073 , -0.060551,
        -0.060343, -0.060134, -0.059925, -0.059713, -0.059494, -0.059255

In [25]:
print(ds.z1[0:10])

<xarray.DataArray 'z1' (yb: 1, xb: 95)>
array([[ 0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
         0.      ,  0.      ,  0.      ,  0.      , -0.081714, -0.081207,
        -0.080675, -0.080142, -0.079659, -0.079269, -0.078878, -0.078427,
        -0.077935, -0.077321, -0.076688, -0.076187, -0.075692, -0.075172,
        -0.074682, -0.074205, -0.073758, -0.073327, -0.072898, -0.072473,
        -0.072089, -0.071694, -0.071298, -0.070906, -0.070539, -0.070185,
        -0.069832, -0.069478, -0.069125, -0.068772, -0.068441, -0.068111,
        -0.06778 , -0.067449, -0.067129, -0.066824, -0.066522, -0.06623 ,
        -0.065944, -0.06566 , -0.065387, -0.065137, -0.064888, -0.06464 ,
        -0.064377, -0.06417 , -0.063967, -0.063759, -0.063552, -0.063348,
        -0.063183, -0.063018, -0.062853, -0.062689, -0.062524, -0.062363,
        -0.062206, -0.062049, -0.061892, -0.061735, -0.061578, -0.061411,
        -0.06124 , -0.06107 , -0.0609  , -0.06073 , -0.060551, -0.060343

In [26]:
print(xds.z1[-10:])

<xarray.DataArray 'z1' (yb: 1, xb: 87)>
array([[ 0.      ,  0.      ,  0.      ,  0.      ,  0.      , -0.081714,
        -0.081207, -0.080675, -0.080142, -0.079659, -0.079269, -0.078878,
        -0.078427, -0.077935, -0.077321, -0.076688, -0.076187, -0.075692,
        -0.075172, -0.074682, -0.074205, -0.073758, -0.073327, -0.072898,
        -0.072473, -0.072089, -0.071694, -0.071298, -0.070906, -0.070539,
        -0.070185, -0.069832, -0.069478, -0.069125, -0.068772, -0.068441,
        -0.068111, -0.06778 , -0.067449, -0.067129, -0.066824, -0.066522,
        -0.06623 , -0.065944, -0.06566 , -0.065387, -0.065137, -0.064888,
        -0.06464 , -0.064377, -0.06417 , -0.063967, -0.063759, -0.063552,
        -0.063348, -0.063183, -0.063018, -0.062853, -0.062689, -0.062524,
        -0.062363, -0.062206, -0.062049, -0.061892, -0.061735, -0.061578,
        -0.061411, -0.06124 , -0.06107 , -0.0609  , -0.06073 , -0.060551,
        -0.060343, -0.060134, -0.059925, -0.059713, -0.059494, -0.059255

In [27]:
print(ds.z1[-10:])

<xarray.DataArray 'z1' (yb: 1, xb: 95)>
array([[ 0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
         0.      ,  0.      ,  0.      ,  0.      , -0.081714, -0.081207,
        -0.080675, -0.080142, -0.079659, -0.079269, -0.078878, -0.078427,
        -0.077935, -0.077321, -0.076688, -0.076187, -0.075692, -0.075172,
        -0.074682, -0.074205, -0.073758, -0.073327, -0.072898, -0.072473,
        -0.072089, -0.071694, -0.071298, -0.070906, -0.070539, -0.070185,
        -0.069832, -0.069478, -0.069125, -0.068772, -0.068441, -0.068111,
        -0.06778 , -0.067449, -0.067129, -0.066824, -0.066522, -0.06623 ,
        -0.065944, -0.06566 , -0.065387, -0.065137, -0.064888, -0.06464 ,
        -0.064377, -0.06417 , -0.063967, -0.063759, -0.063552, -0.063348,
        -0.063183, -0.063018, -0.062853, -0.062689, -0.062524, -0.062363,
        -0.062206, -0.062049, -0.061892, -0.061735, -0.061578, -0.061411,
        -0.06124 , -0.06107 , -0.0609  , -0.06073 , -0.060551, -0.060343